### ISSUE TITLE
Import failing

### ISSUE THREAD

**Issue by summerswallow-whi** [wickedest/mergely-react#4]
I'm by no means an expert in react, but I've been racking my brains trying to figure out why I can't get it to work. It seems to do with the commonJS exporting of the Mergely class.

You're example in the README is not a complete example as it leaves out the importation which is where I'm having issues. Could you at least provide a complete minimal example. 

Thank you.

**Comment by wickedest** [comment]
@summerswallow-whi sorry that you are having trouble. yes, it is a fair point that the documentation is not very good. please tell me what are you using: webpack, next.js, typescrypt? Also tell me the errors you are getting.

**Comment by summerswallow-whi** [comment]
Thanks for responding so quickly.
I'm using the astro with react, but in debugging, I went barebones react. I did the
```npm install mergely-react``` as directed. Here is a basic `App.js` modified after from `create-react-app`
```
import React from 'react';
import MergelyView from 'mergely-react';

function App() {
    return (
        <div style={{ margin: '50px' }}>
            <MergelyView
                height="400px"
                ignorews
                lhs="I like apples!"
                rhs="I like bananas!"
            />
        </div>
    );
}

export default App;
```
Here's the javascript error I get:

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check your code at App.js:7.    at App

printWarning@react-jsx-dev-runtime.development.js:87
```
In my astro/react framework, the error I get also suggests not seeing MergelyView as an export. If you can show me a complete barebones example, I could probably figure out how to get it to work in my environment.

**Comment by wickedest** [comment]
I can't get it to work either. I'll look into it.

**Comment by wickedest** [comment]
@summerswallow-whi, I fixed the issue. It actually required a few changes to mergely, as well as this module to make it work. I updated the README.md with a better example. `mergely-react@1.1.0` should fix your problem.

**Comment by summerswallow-whi** [comment]
Seems to work now. Thanks
